### ISSUE TITLE
KeyError: 'requestContext'

### ISSUE THREAD

**Issue by seanaye** [jordaneremieff/mangum#126]
likely related to #95 

I'm just getting started with serverless in a test application. Im using poetry as python package manager and serverless framework to deploy.

my handler
```python
from mangum import Mangum
from starlette.applications import Starlette
from starlette.responses import PlainTextResponse
from starlette.routing import Route


async def homepage(request):
    response = PlainTextResponse("Hello, world!")

    return response


app = Starlette(debug=True, routes=[Route("/", homepage)])

handler = Mangum(app)
```

my serverless.yml
```
# serverless.yml

org: seanaye
app: my-first-app

service: graphql-test

provider:
  name: aws
  runtime: python3.8

functions:
  graphql:
    handler: lambda_test/handler.handler


plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
```
 
I get 
```
[ERROR] KeyError: 'requestContext'
Traceback (most recent call last):
  File "/var/task/serverless_sdk/__init__.py", line 134, in wrapped_handler
    return user_handler(event, context)
  File "/var/task/mangum/adapter.py", line 110, in __call__
    return self.handler(event, context)
  File "/var/task/mangum/adapter.py", line 130, in handler
    if "eventType" in event["requestContext"]:END RequestId: ef16f1bf-973f-4e9a-95d9-4f2d7af32c23
```

on every `sls invoke -f graphql --log`

**Comment by jordaneremieff** [comment]
This is expected behaviour.

The adapter requires the information in the event and request context to form the ASGI connection scope, or it will not be able to run the application. API Gateway is used to invoke the Lambda function with event data for the specific API type. One thing you might try is invoking the function with test JSON data, but you'll have to consult the Serverless Framework documentation for more details on how to do this.

I can suggest modifying your configuration to include an HTTP API, then when you run `sls deploy` you can open the endpoint URL in your browser:

```
# serverless.yml

org: seanaye
app: my-first-app

service: graphql-test

provider:
  name: aws
  runtime: python3.8

functions:
  graphql:
    - httpApi: '*'
    handler: lambda_test/handler.handler

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
```
Beyond this I can't provide very much more support on Serverless Framework configurations specifically and would have to direct you to https://stackoverflow.com/ or other forums.
