### ISSUE TITLE
Request body empty in FastAPI app that mounts Flask app

### ISSUE THREAD

**Issue by toxygene** [jordaneremieff/mangum#188]
Using Serverless, I'm deploying a FastAPI app to Lambda. The FastAPI app simply mounts a Flask app with a single POST route. When I try to access the request data, it's empty (`b''`) instead of what was submitted.

```
from fastapi import FastAPI
from flask import Flask, request
from mangum import Mangum
from starlette.middleware.wsgi import WSGIMiddleware

flask_app = Flask(__name__)


@flask_app.route("/", methods=["POST"])
def hello_world():
    print(request.data)
    return "Hello, World!"


fastapi_app = FastAPI(debug=True)
fastapi_app.mount("/", WSGIMiddleware(flask_app))

handler = Mangum(fastapi_app)
```

```
service: fastapi-flask-test
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    dockerSsh: true
    usePoetry: true
```

If I run this code via uvicorn, the request body is correct.

```
import uvicorn

from handler import fastapi_app

uvicorn.run(fastapi_app)
```
