### ISSUE TITLE
[QUESTION] - Using serverless framework and test application locally

### ISSUE THREAD

**Issue by fjpa121197** [jordaneremieff/mangum#281]
Is it possible to use serverless framework local invoke feature to test application locally?

I have the following `serverless.yml` file:

```yml

service: property-insights-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  memorySize: 256
  timeout: 30
  iam:
    role: ${file(./myenvs.yml):applicationRole}

  # vpc:
  #   subnetIds:
  #     - ${file(./myenvs.yml):subnets.subnet1}
  #     - ${file(./myenvs.yml):subnets.subnet2}
  #   securityGroupIds:
  #     - ${file(./myenvs.yml):securityGroup}

  stage: dev
  profile: pi-api-dev
  region: eu-west-1
    
functions:
  queryData:
    handler: src/app.handler
    layers:
      - Ref: PythonRequirementsLambdaLayer
    environment: 
      ROLE_TO_ASSUME: ${file(./myenvs.yml):queryDataEnvironmentVariables.ROLE_TO_ASSUME}
    events:
      - http:
          method: get
          path: /
      - http:
          method: any
          path: /{proxy+}

plugins:
  - serverless-python-requirements
  
custom:
  pythonRequirements:
    dockerizePip: true
    layer:
      name: requirements-modules-layer
      compatibleRuntimes:
        - python3.8
      compatibleArchitectures:
        - x86_64
  stage:
    ${opt:stage, self:provider.stage}
    

```

For example, by using `serverless invoke local --function queryData` I want to test the application, and the endpoints, but not sure how to pass the url path I want to test?

My app.py file looks like this:

```python
import boto3
import logging
import os
from mangum import Mangum
from fastapi import FastAPI
from src.api import api

from libs.utils import (
    get_session, sts_assume_dw_role, get_redshift_data_api_client,
    get_query
)



logger = logging.getLogger()
logger.setLevel(logging.INFO)

# Create boto3 session and client to assume role that has permissions to query data warehouse
api_session = get_session()
api_client_stsresponse = sts_assume_dw_role(api_session)
redshift_data_api_client = get_redshift_data_api_client(api_client_stsresponse)


app = FastAPI()

@app.get("/")
def root():

    return {"message": "Hello World"}

app.include_router(api.router, prefix="/api/v1")
handler = Mangum(app, lifespan="off")
```

thanks
